SJang1/korea-covid-19-remaining-vaccine-macro

vaccine-run-kakao.py
* Python에서 사용자의 입력을 받을 때는 무조건 문자열로 받기 때문에 str로 type을 cast할 이유가 없어 제거하였습니다.
* Python 3.6+ 에서 제공되는 f-string을 사용하시면 문자열 더하기하는 방식보다 빠른 속도를 유지할 수 있습니다.
=> Optimize several points

vaccine-run-kakao.py
* 각 기능별 코드가 혼재되어 있어 기능별로 함수를 나누고 이를 실행하도록 했습니다.
* Pygame 과 같은 경우 호환성 이슈가 있어 제거 후 추후 다른 라이브러리를 통해 대체하도록 비활성화했습니다.
* PEP 8에 맞추어 변수 및 함수의 이름을 지정하였습니다.
=> 코드 리팩토링 및 PEP 8에 맞지 않는 코드 변경

vaccine-run-kakao.py
* Config.ini 가 같은 폴더 안에 없을 때 튕기던 문제 수정
=> resolve problem when no config.ini in directory

.gitignore, vaccine-run-kakao.py
* #217 해당 이슈를 수정한 커밋을 포함한 Pull request입니다.
=> Tada 사운드를 재생할 수 있는 함수 수정

.github/workflows/package.yml
Windows 빌드만 적용했습니다.
Close #240 
부연설명: requirements-dev.txt가 pyinstaller를 설치해서, windows 빌드에서는 제외하였습니다.
=> ci: Build own pyinstaller bootstrap for windows.

.github/workflows/package.yml
https://github.com/MPThLee/korea-covid-19-remaining-vaccine-macro/runs/3176982255?check_suite_focus=true
https://www.virustotal.com/gui/file/45920c7790a46134032d2a029aa67b0db87828b5e106d35a5bb1394aeb9f6c19/detection
Temp fix for #303
=> ci: Force x86 with own v4.3 bootloader on windows

.github/workflows/package.yml
Reverts SJang1/korea-covid-19-remaining-vaccine-macro#320
변한 게 없으므로 Revert 합니다.
=> Revert "ci: Force x86 with own v4.3 bootloader on windows"

vaccine-run-kakao.py
In response to issue #359 :
response.text를 find_vaccine의 try/except 안에서 먼저 parsing을 해서 JSONDecodeError를 catch합니다.
pretty_print도 string argument에서 parse된 json object를 받게끔 수정합니다.
=> Fix uncaught json decode error and minor change to pretty_print

vaccine-run-kakao.py
find vaccine 리퀘스트가 많다보니 가끔 서버단에서 응답이 좀 많이 늦어지는 경우가 있는데(아예 사실상 씹히는 경우도 있습니다.), 이때만은 다시 시도하도록 변경했습니다.
5초로 설정했습니다.
=> feat: Set timeout for find vaccine

requirements.txt, telegram.txt, vaccine-run-kakao.py
동일 폴더 내에 **'telegram.txt'** 파일이 있으면
해당 파일의 token=[토큰값], chatid=[ChatID]를 불러와 예약 성공 시 Telegram을 통하여 예약 성공 Messgae를 보내게 하였습니다.
**telegram.txt Example**
[telegram]
token = asdfaqweqrasdafgqasdad
chatid = 12345678
=> 예약성공 시 Telegram Bot을 이용한 Message 발송

vaccine-run-kakao.py
백신타입 오타가 나서 하나 놓쳤네요
저같은 사람 또 안나오도록 수정했습니다
=> 백신 타입 검증 로직 추가

.github/workflows/lint.yml, .prospector.yaml, vaccine-run-kakao.py
코드스타일 및 static check 도입.
[Prospector](https://prospector.landscape.io/)를 사용합니다.
=> ci: Python lint

vaccine-run-kakao.py
=> feat: Show warning on unused vaccine code

vaccine-run-kakao.py
Report: #654
Upstream bug: psf/requests#5430
원래는 `requests.exceptions.Timeout`이 나야하는데 `requests.exceptions.ConnectionError`가 나는 현상입니다...
=> fix: Attempt to fix weird timeout bug on requests

vaccine-run-kakao.py
VENxxxxx 형식이 맞는지 체크도 한번 더 합니다. 바뀔 수도 있으니 유저 확인도 한번 더 받습니다.
=> feat: check vaccine code is valid on force mode

vaccine-run-kakao.py
fix #680
위에 value 검색 코드 복사해서 생긴 문제인데 모르고 넘어갔네요 ㅠㅠ
=> fix: Fix unused vaccine code checker

vaccine-run-kakao.py
이미 예방접종이 완료된 사용자인 경우에는 사운드를 플레이 하지 않고, 텔레그렘 메세지 전송을 하지 않습니다.
~~또한 사운드 플레이시 플레이 동안 Thread가 블로킹이 되는데, `block=False`를 줘서 수정했습니다.~~ 제 시스템에서 재생이 안되는 버그가 있네요;;
=> fix: Do not play sound on non-error

README.md
공지사항 링크 추가.
PS. 공지사항에 `Archaive`가 아니라 `Archive` 입니다..
=> chore: Update READMD.md [skip ci]

vaccine-run-kakao.py
사용자가 입력한 xy 좌표값을 체크합니다.
top 입력 때는 대한민국 범위 내면 pass하며 bottom 입력 때는 top_x보다 작거나, top_y보다 큰 경우에도 재입력하게끔 합니다.
=> Check input coordinates

.github/workflows/package.yml
So give it all dependencies in a single command so it can detect and resolve conflicts.
=> package.yml: pip has a dependency resolver

vaccine-run-kakao.py
https://github.com/SJang1/korea-covid-19-remaining-vaccine-macro/issues/786
=> 잔여 백신만 있는 병원을 불러오도록 수정

kakao/cookie.py, kakao/user.py
Fixes #835 , which was due to previous usage of global `jar` variable.
=> fix: 반복 쿠키 권한 요청

docs/build.md
=> Update build.md [skip ci]

kakao/request.py, vaccine-run-kakao.py
=> hotfix: Remove recursion in `find_vaccine`

kakao/request.py
#942 관련해서 vaccine_type이 ANY가 아닌 경우 선택한 백신의 leftCount가 0이 아닐 경우에만 try_reservation를 요청하는 코드입니다.
더불어 잔여 백신이 검색된 병원 전체를 순차적으로 탐색합니다.
급하게 짠거라 검증은 아직 되지 않았습니다. 
확인 후 머지 부탁드립니다.
=> 백신을 선택한 경우 해당 백신이 존재하면 try_reservation 하기, 다른 병원도 찾아보고 요청하기

kakao/request.py
=> Performance improvement (PR #968)

docs/build.md
파일명 업데이트 사항이 빌드 명령어에 반영되지 않았길래 수정했습니다.
=> docs: Fix wrong build command

kakao/config.py
1.1.0 업데이트로 인한 [#1045 Comment](https://github.com/SJang1/korea-covid-19-remaining-vaccine-macro/issues/1045#issuecomment-897297463) 문제를 해결합니다.
=> fix: Print vaccine types from config

docs/login.md
쿠키값주소가 기존에 vaccine.kakao에서 -> vaccine-map.kakao로 바뀌었네요
=> 쿠키값 주소 변경에 따른 README.md 변경 제안
